- hosts: web
  tasks: 
  - name: "sync website"
    synchronize:
      src: /home/wahid/ajk/site/
      dest: /var/www/ajk.id
      archive: no
      checksum: yes
      recursive: yes
      delete: yes
    become: no